### ISSUE TITLE
Looking for a new maintainer to take over this repository

### ISSUE THREAD

**Issue by colinkiama** [colinkiama/hare-sublime-syntax#3]
I don't see myself being able to continue working on this project in the future. It''s been abandoned for a while.

It would be great if someone else picked it up. [Hare](https://harelang.org/) is an awesome upcoming programming language after all!

**Comment by alecGraves** [comment]
I would be willing to take it over if you are not able to spend much time on the plugin. I am actively using it for my Hare projects, so it would be pretty convenient for me.

**Comment by colinkiama** [comment]
Great!

It's not letting me do so right now since you have a fork of the repository with the same name.

Please let me know when you've either renamed or deleted the repository so I can send you a repository transfer request.

**Comment by alecGraves** [comment]
Ok, I renamed my fork. Thanks.

**Comment by colinkiama** [comment]
Oops sorry, they want you to delete it:
![image](https://github.com/colinkiama/hare-sublime-syntax/assets/16501024/de31a61d-392c-47f0-866b-372756e8c04a)

**Comment by alecGraves** [comment]
Ahh, ok. Deleted. Thanks!

**Comment by colinkiama** [comment]
Sent the transfer request

**Comment by alecGraves** [comment]
Great, looks like it worked. Thanks for starting this minimal Hare plugin @colinkiama; I look forward to taking care of it.
